table despesas_raw
	lineageTag: d78030ae-8ac6-4914-acd4-455da922267a

	column despesa_id
		dataType: string
		lineageTag: 448388bb-bdde-4c66-a615-744f54c2f75c
		summarizeBy: none
		sourceColumn: despesa_id

		annotation SummarizationSetBy = Automatic

	column viagem_id
		dataType: string
		lineageTag: cfbf350f-7c7a-44b1-b822-530e37beead7
		summarizeBy: none
		sourceColumn: viagem_id

		annotation SummarizationSetBy = Automatic

	column categoria
		dataType: string
		lineageTag: 9e4e76c6-69fe-4ea9-9792-36bee0536e19
		summarizeBy: none
		sourceColumn: categoria

		annotation SummarizationSetBy = Automatic

	column valor
		dataType: double
		lineageTag: 059d2c0b-00cf-488f-9dc4-422e2adfa444
		summarizeBy: sum
		sourceColumn: valor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column data_despesa
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4d3f65a0-e342-4d9c-9e03-ccd9979875cb
		summarizeBy: none
		sourceColumn: data_despesa

		variation Variation
			isDefault
			relationship: 2cc0e8b8-eca9-4cf8-8cb6-493b14bd5c1c
			defaultHierarchy: LocalDateTable_3d513005-4b36-4070-b10c-bb528e51fc92.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column reembolsavel
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a5b63b25-c4ed-4201-85db-8475b6e8ceec
		summarizeBy: none
		sourceColumn: reembolsavel

		annotation SummarizationSetBy = Automatic

	partition despesas_raw = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\DELL\Documents\Projetos\Github\Dashboard Viagens Corporativas\despesas_raw.csv"),[Delimiter=",", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado com Localidade" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos", {{"valor", type number}}, "en-US"),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Tipo Alterado com Localidade",{{"data_despesa", type date}, {"reembolsavel", type logical}}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Tipo Alterado", {"despesa_id"})
				in
				    #"Duplicatas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

